apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: hello-world-connected-topology
  labels:
    "app.kubernetes.io/instance": "react-web-app"
spec:
  tasks:
    - name: hello-world
      taskRef:
        name: hello-world
