apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: broken-app-pipeline
spec:
  tasks:
    - name: install-deps
      taskRef:
        name: install-dependencies-2
    - name: code-sanity
      taskRef:
        name: lint-and-test-2
      runAfter:
        - install-deps
    - name: x-compile
      taskRef:
        name: build-dist-2
      runAfter:
        - install-deps
    - name: e2e-tests
      taskRef:
        name: run-e2e-tests-2
      runAfter:
        - code-sanity
        - x-compile
