apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: install-dependencies-2
spec:
  steps:
    - name: install
      image: ubuntu
      command:
        - echo
      args:
        - "Installing dependencies...\n\nDependencies installed successfully."
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: lint-and-test-2
spec:
  steps:
    - name: startup
      image: ubuntu
      command:
        - echo
      args:
        - "Running Linter and Tests"
    - name: lint-errors
      image: ubuntu
      command:
        - echo
      args:
        - "0 Lint Errors"
    - name: test-status
      image: ubuntu
      command:
        - echo
      args:
        - "0 Test Failures"
    - name: coverage-report
      image: ubuntu
      command:
        - echo
      args:
        - "Exporting Test Coverage Report...\n\nCoverage report can be found in __coverage__"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-dist-2
spec:
  steps:
    - name: build
      image: ubuntu
      command:
        - alksdjf
      args:
        - "Compiling code and producing dist folder...\n\nFolder public/dist created"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run-e2e-tests-2
spec:
  steps:
    - name: status
      image: ubuntu
      command:
        - echo
      args:
        - "Running end-to-end tests...\n\nAll tests pass"
