apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: pipeline-simple-snippet
spec:
  targetResource:
    apiVersion: tekton.dev/v1alpha1
    kind: Pipeline
  title: Simple Task
  description: An example of a simple task snippet
  snippet: true
  yaml: |
    - name: hello-world
      taskRef:
        name: hello-world