apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-task
spec:
  params:
    - name: echo-value-for-task
      description: The value to echo out
      default: this is not the param you're looking for
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "$(inputs.params.echo-value-for-task)"
